Kullanıcı Şifresi Hashlendi
esogu-ceng/school-app-backend pull request #10
Opened 2023-11-04 21:28 UTC by iremkvkpnr

## Gereksinimler
Kullanıcı şifresinin güvenlik açısından hashlenerek veri tabanına kaydedilmesi gerekiyordu.

## Çözüm
UserService.java dosyasına hash kütüphanesi eklenerek passwordun hashlenerek veri tabanına kaydedilmesi sağlandı.

2023-11-05 14:06 UTC, ykartal requested changes

2023-11-05 14:06 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/service/UserService.java
> +		String plainPassword = password; // Kullanıcının girdiği şifre
Neden doğrudan üstteki password değişkeninin adı değiştirilmedi?

2023-11-05 14:06 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/service/UserService.java
> +        user.setPassword(hashedPassword);
Indentation'a da dikkat etmeliyiz.

2023-11-07 11:37 UTC, iremkvkpnr commented on src/main/java/tr/ogu/edu/school/schoolapp/service/UserService.java
> +		String plainPassword = password; // Kullanıcının girdiği şifre
düzeltip pushlayacağım hocam.

2023-11-07 15:20 UTC, mukrime-s commented on src/main/java/tr/ogu/edu/school/schoolapp/service/UserService.java
> +		String plainPassword = user.getPassword();// Kullanıcının girdiği şifre
isim olarak "password" kullanmak daha doğru olur.

2023-12-01 11:56 UTC, merged