Ayarlar tablosu oluşturularak ilgili paketlere geliştirmeler tamamlandı
esogu-ceng/school-app-backend pull request #12
Opened 2023-11-05 21:36 UTC by mukrime-s

### Gereksinimler
Kullanıcının sistemde ayarları bulunmamaktaydı.
### Çözüm
Ayarlar  için gerekli paketler oluşturuldu ve uygun şekilde kodlandı.

2023-11-06 05:41 UTC, ykartal requested changes
1. target klasörü silinip gitignore'a eklenmeli.
2. DTO için kurulan yapı tamamlanmalı ve kullanılmalı.

2023-11-06 05:41 UTC, ykartal commented on .gitignore
> +target/classes/META-INF/maven/tr.ogu.edu.school/school-app/pom.properties
target klasörü tamamen bu dosyaya eklenmeli.
target

2023-11-06 05:41 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/dto/SettingDto.java
> +}
controller'da dto kullanılmamış, kullanılacaksa dto'nun üye verileri eksik.

2023-11-06 05:41 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/mapper/SettingMapper.java
> +		return setting;
bu metotlar dönüşüm yapmıyorlar.

2023-11-07 11:33 UTC, ykartal approved these changes

2023-11-09 18:23 UTC, iremkvkpnr approved these changes

2023-11-10 10:36 UTC, hsynkmk approved these changes

2023-11-10 11:39 UTC, merged