Ödenen ve ödenmeyen taksitler listelendi.
esogu-ceng/school-app-backend pull request #36
Opened 2024-01-30 10:24 UTC by iremkvkpnr

# Problem:
Ödenen ve ödenmeyen taksitlerin listelenmesi isteniyordu.

# Çözüm:
Installement tablosunda toplam taksit tutarı amount adı altında tutuluyordu fakat ödenen taksit tutarı bulunmuyordu. Paid_amount eklenerek ödenen taksit tutarının da tutulması sağlandı. 
Paid_amount ile amountun karşılaştırılarak taksit miktarının ödenip ödenmediğinin listelenmesi sağlandı.

2024-01-30 12:26 UTC, ykartal requested changes

2024-01-30 12:26 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/service/InstallmentService.java
> +        }
Bu şekilde bir kontrole gerek olmadan veritabanı sorgusu ile çekilemez miydi?

2024-01-31 21:52 UTC, ykartal commented on school-app-db-script/school-app04.sql
> +ADD COLUMN paid_amount DOUBLE PRECISION DEFAULT 0.0;
Seni biaz uğraştırmış olacağız ama veritabanında payment diy bir tablo var. Yani burada şöyle düşünülmüş. Taksitler ve tutarları Installment tablosunda tutulsun.Yapıan ödemeler de payment tablosunda tutulsun. Ödenen ve kalan taksitler hesaplama yapılarak tespit edilsin. Parçalı olarak ödenen kısımlarında hangi tarihte ne kadar şeklinde olduğu kayıtaltında dursun. Bu sebeple bu şekilde bir alana ihtiya duyulmuyor diyebiliriz.

2024-02-04 15:58 UTC, iremkvkpnr commented on school-app-db-script/school-app04.sql
> +ADD COLUMN paid_amount DOUBLE PRECISION DEFAULT 0.0;
hocam istediğiniz şekilde yaptım ama ödenen miktarlarında hangi tarihte ne kadar olduğunun da dönmesini isterseniz ona göre bir query yazıp object array seklinde döndürebilirim.

2024-02-04 16:39 UTC, iremkvkpnr commented
conflict çözerken installment.java dosyasını bi önceki haline döndürmüşüm sanırım. Kontrol edebilir misiniz?

2024-02-04 16:59 UTC, mukrime-s commented
> conflict çözerken installment.java dosyasını bi önceki haline döndürmüşüm sanırım. Kontrol edebilir misiniz?

Evet bir önceki haline döndürmüşsün geri alman gerekecek

2024-02-05 06:59 UTC, Yasin-Gok submitted a review, later dismissed

2024-02-05 17:04 UTC, iremkvkpnr commented
> > conflict çözerken installment.java dosyasını bi önceki haline döndürmüşüm sanırım. Kontrol edebilir misiniz?
> 
> Evet bir önceki haline döndürmüşsün geri alman gerekecek
Kontrol

2024-02-10 19:32 UTC, ykartal approved these changes

2024-02-10 19:32 UTC, merged