Bilet oluşturup pdf metodu çağırıldı
esogu-ceng/school-app-backend pull request #49
Opened 2024-02-07 11:59 UTC by Yasin-Gok

2024-02-07 12:23 UTC, ykartal requested changes

2024-02-07 12:23 UTC, ykartal commented on src/main/resources/application.properties
> +spring.datasource.password=VTYS78.
bu dosyadaki bilgileri değiştirmemeliyiz?

2024-02-07 12:23 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/service/ActTicketService.java
> +    public List<ActTicket> getAllActTickets() {
Bu metodu kaldıralım, böyle bir metoda ihtiyaç olmamalı. olursa sayfalı yapıda getirilir.

2024-02-07 12:23 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/service/ActTicketService.java
> +            System.out.println("Bilet null olduğu için kayıt yapılamadı ve PDF üretilemedi.");
TODO Burada uygun şekilde exception fırlatılmalı. ve slf4j ile log yazılmalı.

2024-02-07 12:23 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/repository/ActTicketRepository.java
> +    List<ActTicket> getAllActTickets();
Bu metoda ihtiyacımız olmamalı.

2024-02-07 12:23 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/controller/ActTicketController.java
> +    }
Böyle bir metoda ihtiyacımız olmamalı.

2024-02-07 12:23 UTC, ykartal commented on package.json
Backend tarafında neden böyle bir dosyaya ihtiyacımız var? silinmeli.

2024-02-07 13:37 UTC, oguntosee commented on package.json
> +}
package.json Frontend ile ilgili değil mi?

2024-02-07 14:12 UTC, Yasin-Gok commented
O değişilmesi gereken durumları değiştirdim.

2024-02-07 14:13 UTC, Yasin-Gok commented on package.json
> +}
Bir ara hata olmuştu onu çözmeye çalışırken kalmış orda büyük ihtimalle

2024-02-07 18:49 UTC, ykartal commented on package.json
> +}
Hala duruyor ama dosya, bunu silip commit yapmalısın

2024-02-07 19:54 UTC, Yasin-Gok commented on package.json
> +}
Şuan silinmiş olması lazım

2024-02-08 02:29 UTC, ykartal requested changes

2024-02-08 02:29 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/controller/ActTicketController.java
> +    }
Constructor'ı yazmak yerine clean-code için lombok kullanıyoruz ve sınıfın üzerine örneğin @RequiredArgsConstructor ekliyoruz.

2024-02-08 02:29 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/repository/ActTicketRepository.java
> +    // Sorgular
Gereksiz yorum satırlarını eklememeliyiz.

2024-02-08 02:29 UTC, ykartal commented on src/main/java/tr/ogu/edu/school/schoolapp/service/ActTicketService.java
> +            throw new FileNotFoundException("Bilet bulunamadı");
```suggestion
            throw new TicketRequiredException("Kaydedilecek bir bilet verisi gönderilmedi.");
```

benzeri bir Exception sınıfı oluşturularak gönderilmeli.

2024-02-08 12:46 UTC, Yasin-Gok commented
Lombok ve exception sınıfı eklendi

2024-02-08 16:13 UTC, Yasin-Gok commented on src/main/java/tr/ogu/edu/school/schoolapp/controller/ActTicketController.java
> +@RequestMapping("/act-tickets")
Tamamdır o şekilde değiştim

2024-02-08 17:14 UTC, mukrime-s approved these changes

2024-02-09 07:09 UTC, iremkvkpnr approved these changes

2024-02-09 08:38 UTC, ykartal approved these changes

2024-02-09 08:38 UTC, merged